sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: UjDfGsYEucW1Ii9mSdKMO3o5u/t8TD2i1ZEXdtJWVdqNrVLkJPoAAQnXCxP8xp/bQWzYrcjsjoM/QTk325EMD6yVHS/3gp3e6A4P9DK1EzbYm9PfYnKK7Hdlj1+Vf9/C2Z/P0GdFcLj23cPldgyCP8P1UPx0NK3Tnrve0hsbsq2AhyiaZsBD/i9MCkY18OPTt6c8Nc3uqaKo9pUeflcm9eOK0XCV1Nas4r/nOskfo0N9JACiXHb8KavJSYupum1twEdpO9I+S0icHUo/0xA9hitGOaxTyrnUde2z8Qkm9apO97UQKzcpn/1pnCjrgS36cXJbUNdz8rDkfOWFV1S3kKhejwWwCqIz4MkGn1ls3yjSSpJW+P+M6ELXn8guy88b0z6KP6LY0RAWPbniGf49B8xEVt6g4OqNx8K53k39MgCNld2aygMpzPJw9Qnf9XON2ZXPdiCQB2jUXjJotQdBeIh6z7sQqrF7gw9Mfki/+cH7IViAblJ3aiA/MfIiT/gC3aXkBlelighPlVB1g6l6Slu489WX5QxBHkO11+WAnN8H7C+zVr3lpg0aD49zkbKjFZGjLXLKKCY08p6nMG09G5K75S56063pqrrQGLaIuSfITu/OZhs1mDxFFDwSvv9wu5mntBHLViX4pOicGgojtf+VxOOhRo4qEtrOkI7gU90=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: s7iLsiLt8FU1wkpwbVvnJuxtlZsft+oN55u4ImIrdpePbzDAZbwrQUofRx3MlHNYXA9ceglViqOB3xNgy9WjRm7RSIzOkpL6MNcS8+Zm9iAMnuMcl7lRWiKHeWK875LGbKKV+Onf8K70ugM+k3rbj88vzwR3V6dsozwUBilkoIqQGlh89uoR/76cX5kD7zlLCfsBUc60N12P6OrdBwARjFKJfXYfVojewfuYJcbri48eNjkqOsz8UuBmFdBJlgHW26SNIdm08OJbp2t06LCfqYL9d0sS9hbTZCno5Op+KzFB2xEcyG8eczBPjyEZC3NM2k0CvQ437wXq+WWYlyp3tF06QtMQQdlbKxtjTo2o94K0tF8VKjJeHNsayJbxbD+gWcAet72WfkMBr0T5X+QfYvdRrJXN4f/tkR+LNMY58ALlcs40zFtLdl9/8cFUXkU86Q1CGolABNIpdlhLNa+MOoEgh6pJQz1cFL4qy1zSFUyONUN/dYpvL3HJK28f3dNU31vzbt5xx1F6Y7yLVRFkS4ubcuHx86b8/HOG0m2JgSKGLW+0yjlk3IsmYEEXicMToViRGBycPgjOSRCvaN5dEmEHVX0G7c0F+6chlvhqEIuEjAjyhenaZFjYYiADo9AAeY7YByndsyZhRnkZdBD9WqYaVGV1EWhqeVO2j+Dj/T8=
